### ISSUE TITLE
Qvibe window too wide?

### ISSUE THREAD

**Issue by JanSam** [3ll3d00d/qvibe-analyser#39]
When opening qvibe it fills the whole screen side to side, and i can not drag it more narrow? So i can’t make the window smaller to have more windows(like REW generator and/or Minidsp app) open at the same time.

I could swear this worked on earlier versions?

**Comment by JanSam** [comment]
Ohh, i am on Mac, BTW.

**Comment by 3ll3d00d** [comment]
I see a minimum width of 1100px here 

what resolution screen do you have?

**Comment by JanSam** [comment]
2560 x 1600

**Comment by JanSam** [comment]
Do you see these pics ?
![IMG_1636](https://user-images.githubusercontent.com/28634829/66713041-ce6ac000-eda5-11e9-837e-ee79de2c81fd.jpeg)
![IMG_0946](https://user-images.githubusercontent.com/28634829/66713050-ef331580-eda5-11e9-87b1-8db5d4f16142.png)

**Comment by JanSam** [comment]
Top shows no "no less width available arrow" and bottom one show qvibe actually to big for screen.

**Comment by 3ll3d00d** [comment]
the ui widgets look pretty big on your screen, do you have some increased scaling on? like http://osxdaily.com/2016/05/23/increase-system-text-size-mac-os-x-scaled-resolution/

**Comment by JanSam** [comment]
Actually no, but i can actually use your link there to make it smaller, so thanks :)

**Comment by 3ll3d00d** [comment]
0.4.1 has an update which *should* allow you to reduce the width as the controls will flow onto multiple rows if required
